# Numpy Assignment

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

In [39]:
import pandas as pd
import numpy as np

In [40]:
x=np.array([1,3,4,5,6])
n=5
matrix=np.vander(x,n,increasing=False)
print(matrix)

[[   1    1    1    1    1]
 [  81   27    9    3    1]
 [ 256   64   16    4    1]
 [ 625  125   25    5    1]
 [1296  216   36    6    1]]


The moving average sequence has n-k+1 elements as shown below.

In [41]:
matrix=np.vander(x,n,increasing=True)
print(matrix)

[[   1    1    1    1    1]
 [   1    3    9   27   81]
 [   1    4   16   64  256]
 [   1    5   25  125  625]
 [   1    6   36  216 1296]]


The moving averages with k=4 of a ten-value sequence (n=10) is shown below

In [42]:
def movingAverage(inputValue, k):
  z = 1
  output = np.convolve(inputValue, np.ones(k), 'valid') / k
  for i in output:
    print("y{0} = {1:.2f}".format(z, i))
    z += 1

In [43]:
inputValue = np.array([10,20,30,40,50,60,70,80,90,100])
k = 4
movingAverage(inputValue, k)

y1 = 25.00
y2 = 35.00
y3 = 45.00
y4 = 55.00
y5 = 65.00
y6 = 75.00
y7 = 85.00


Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [44]:
inputValue = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3
movingAverage(inputValue, k)

y1 = 5.00
y2 = 4.67
y3 = 5.67
y4 = 6.67
y5 = 9.67
y6 = 28.67
y7 = 49.33
y8 = 72.67
y9 = 84.00
y10 = 93.33
y11 = 116.33
